<?php
$field = static function (string $key, mixed $default = '') use ($editing): mixed { return old($key, $editing[$key] ?? $default); };
$isActive = (int) old('active', $editing['active'] ?? 1) === 1;
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Badge management</h1><p class="text-muted mb-0">Configure measurable conservation milestones awarded after verification.</p></div><?php if ($editing): ?><a class="btn btn-outline-secondary" href="<?= e(url('admin/badges.php')) ?>">Add another badge</a><?php endif; ?></div>
<div class="row g-4">
    <div class="col-lg-5"><form class="card" method="post" action="<?= e(url('admin/badges.php')) ?>"><div class="card-header"><h2 class="h5 mb-0"><?= $editing ? 'Edit badge' : 'Add badge' ?></h2></div><div class="card-body">
        <?= Csrf::field() ?><input type="hidden" name="action" value="save"><?php if ($editing): ?><input type="hidden" name="id" value="<?= (int) $editing['id'] ?>"><?php endif; ?>
        <div class="mb-3"><label class="form-label" for="badge-code">Code</label><input class="form-control text-uppercase" id="badge-code" name="code" pattern="[A-Za-z0-9_-]{2,60}" maxlength="60" required value="<?= e($field('code')) ?>" placeholder="FIRST_REPORT"></div>
        <div class="mb-3"><label class="form-label" for="badge-name">Badge name</label><input class="form-control" id="badge-name" name="badge_name" maxlength="120" required value="<?= e($field('badge_name')) ?>"></div>
        <div class="row g-3 mb-3"><div class="col-sm-7"><label class="form-label" for="badge-metric">Metric</label><select class="form-select" id="badge-metric" name="metric" required><?php foreach ($metrics as $key => $label): ?><option value="<?= e($key) ?>" <?= $field('metric') === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="col-sm-5"><label class="form-label" for="badge-target">Target</label><input class="form-control" type="number" min="1" id="badge-target" name="target_value" required value="<?= e($field('target_value', 1)) ?>"></div></div>
        <div class="mb-3"><label class="form-label" for="badge-description">Description</label><textarea class="form-control" id="badge-description" name="description" maxlength="255" rows="3" required><?= e($field('description')) ?></textarea></div>
        <div class="mb-3"><label class="form-label" for="badge-image">Image path</label><input class="form-control" id="badge-image" name="image_path" maxlength="255" value="<?= e($field('image_path')) ?>" placeholder="img/badges/example.png"></div>
        <input type="hidden" name="active" value="0"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="badge-active" name="active" value="1" <?= $isActive ? 'checked' : '' ?>><label class="form-check-label" for="badge-active">Badge can be earned</label></div>
    </div><div class="card-footer"><button class="btn btn-success" type="submit"><?= $editing ? 'Save changes' : 'Create badge' ?></button></div></form></div>
    <div class="col-lg-7"><div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Badge</th><th>Rule</th><th>Earned</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
        <?php foreach ($badges as $badge): ?><tr><td><strong><?= e($badge['badge_name']) ?></strong><div class="small text-muted"><?= e($badge['code']) ?></div><div class="small"><?= e($badge['description']) ?></div></td><td><?= e($metrics[$badge['metric']] ?? $badge['metric']) ?> &ge; <?= number_format((int) $badge['target_value']) ?></td><td><?= number_format((int) $badge['earned_count']) ?></td><td><span class="badge <?= (int) $badge['active'] === 1 ? 'text-bg-success' : 'text-bg-secondary' ?>"><?= (int) $badge['active'] === 1 ? 'Active' : 'Inactive' ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-success" href="<?= e(url('admin/badges.php?edit=' . $badge['id'])) ?>">Edit</a> <form class="d-inline js-confirm-form" data-confirm="Delete this unearned badge?" method="post" action="<?= e(url('admin/badges.php')) ?>"><?= Csrf::field() ?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= (int) $badge['id'] ?>"><button class="btn btn-sm btn-outline-danger" type="submit">Delete</button></form></td></tr><?php endforeach; ?>
        <?php if ($badges === []): ?><tr><td colspan="5" class="text-center text-muted py-5">No badges configured.</td></tr><?php endif; ?>
    </tbody></table></div></div></div>
</div>
<script src="<?= e(asset('js/admin.js')) ?>" defer></script>
