<?php
$mapData = ['lat' => (float) $cluster['center_lat'], 'lng' => (float) $cluster['center_lng'], 'name' => $cluster['name'], 'radius' => (int) $cluster['radius_meters']];
$chartData = ['labels' => array_column($survivalPoints, 'date'), 'rates' => array_column($survivalPoints, 'rate'), 'alive' => array_column($survivalPoints, 'alive')];
$latestAlive = $survivalPoints === [] ? null : $survivalPoints[array_key_last($survivalPoints)]['alive'];
$latestRate = $survivalPoints === [] ? null : $survivalPoints[array_key_last($survivalPoints)]['rate'];
?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><a class="small text-decoration-none" href="<?= e(url('admin/cluster.php')) ?>">&larr; All clusters</a><h1 class="h3 mb-1 mt-2"><?= e($cluster['name']) ?></h1><div class="text-muted"><?= e($cluster['cluster_code']) ?> · <?= e($cluster['barangay_name']) ?><?= $cluster['sitio_name'] ? ' · ' . e($cluster['sitio_name']) : '' ?></div></div><a class="btn btn-outline-success" href="<?= e(url('admin/analytics.php?barangay_id=' . $cluster['barangay_id'])) ?>">Barangay analytics</a></div>

<div class="row g-3 mb-4">
    <div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><div class="text-muted small">Current health</div><div class="h3"><span class="badge <?= e(health_class($cluster['latest_health'])) ?>"><?= e($cluster['latest_health']) ?></span></div><div class="small text-muted">Updated <?= e(format_datetime($cluster['latest_report_at'])) ?></div></div></div></div>
    <div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><div class="text-muted small">Latest survival</div><div class="display-6"><?= $latestRate === null ? 'N/A' : e(number_format((float) $latestRate, 1) . '%') ?></div><div class="small text-muted"><?= $latestAlive === null ? 'Alive count unavailable' : number_format((int) $latestAlive) . ' of ' . number_format((int) $cluster['initial_seedlings']) ?></div></div></div></div>
    <div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><div class="text-muted small">Verified reports</div><div class="display-6"><?= number_format((int) $cluster['verified_count']) ?></div><div class="small text-muted"><?= count($timeline) ?> total linked reports</div></div></div></div>
    <div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><div class="text-muted small">Species / rarity</div><strong><?= e($cluster['species_name'] ?: ($cluster['scientific_name'] ?: 'Unassigned')) ?></strong><div class="small fst-italic"><?= e($cluster['scientific_name'] ?: '') ?></div><div class="badge text-bg-light mt-2"><?= e($cluster['rarity_level']) ?></div></div></div></div>
</div>

<div class="row g-4 mb-4"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h2 class="h5 mb-0">Monitoring area</h2></div><div id="cluster-map" style="height:380px"></div><div class="card-footer small text-muted">Center <?= e($cluster['center_lat']) ?>, <?= e($cluster['center_lng']) ?> · assignment radius <?= number_format((int) $cluster['radius_meters']) ?> m</div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h2 class="h5 mb-0">Survival trend</h2></div><div class="card-body"><?php if ($survivalPoints !== []): ?><canvas id="cluster-survival-chart"></canvas><?php else: ?><div class="d-flex align-items-center justify-content-center h-100 text-center text-muted py-5">Survival appears after a verified report records an alive count and the cluster has initial seedlings.</div><?php endif; ?></div></div></div></div>

<div class="card"><div class="card-header"><h2 class="h5 mb-0">Observation timeline</h2></div><div class="card-body">
<?php if ($timeline !== []): ?><div class="vstack gap-3"><?php foreach ($timeline as $report): ?><article class="border rounded p-3"><div class="d-flex flex-wrap justify-content-between gap-2"><div><a class="fw-semibold" href="<?= e(url('admin/report.php?id=' . $report['id'])) ?>"><?= e($report['report_code']) ?></a> <span class="badge <?= e(report_status_class($report['status'])) ?>"><?= e(ucfirst($report['status'])) ?></span><?php if ((int) $report['needs_attention'] === 1): ?> <span class="badge text-bg-danger">Attention</span><?php endif; ?></div><time class="small text-muted"><?= e(format_datetime($report['submitted_at'])) ?></time></div><div class="row g-2 mt-1"><div class="col-sm-3"><span class="text-muted small">Health</span><div><span class="badge <?= e(health_class($report['final_health'] ?: $report['suggested_health'])) ?>"><?= e($report['final_health'] ?: $report['suggested_health']) ?></span></div></div><div class="col-sm-3"><span class="text-muted small">Species</span><div><?= e($report['species_name'] ?: 'Unassigned') ?></div></div><div class="col-sm-3"><span class="text-muted small">Alive</span><div><?= $report['observed_alive_count'] === null ? 'Not recorded' : number_format((int) $report['observed_alive_count']) ?></div></div><div class="col-sm-3"><span class="text-muted small">Guardian</span><div><?= e($report['guardian_name']) ?></div></div></div><?php if ($report['expert_feedback']): ?><div class="alert alert-light mt-3 mb-0 py-2"><strong>Expert feedback:</strong> <?= nl2br(e($report['expert_feedback'])) ?></div><?php endif; ?></article><?php endforeach; ?></div><?php else: ?><p class="text-center text-muted py-5 mb-0">No reports are linked to this cluster.</p><?php endif; ?>
</div></div>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha384-sHL9NAb7lN7rfvG5lfHpm643Xkcjzp4jFvuavGOndn6pjVqS6ny56CAt3nsEVT4H" crossorigin="anonymous">
<script>window.mangroovesCluster = <?= json_encode(['map' => $mapData, 'chart' => $chartData], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js" integrity="sha384-vsrfeLOOY6KuIYKDlmVH5UiBmgIdB1oEf7p01YgWHuqmOHfZr374+odEv96n9tNC" crossorigin="anonymous" defer></script>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha384-cxOPjt7s7Iz04uaHJceBmS+qpjv2JkIHNVcuOrM+YHwZOmJGBXI00mdUXEq65HTH" crossorigin="anonymous" defer></script>
<script src="<?= e(asset('js/admin.js')) ?>" defer></script>
