<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Mangrove clusters</h1><p class="text-muted mb-0">Inspect each verified monitoring area and open its observation timeline.</p></div><a class="btn btn-outline-success" href="<?= e(url('admin/analytics.php')) ?>">Analytics map</a></div>
<form class="card card-body mb-4" method="get" action="<?= e(url('admin/cluster.php')) ?>"><div class="row g-3 align-items-end">
    <div class="col-md-3"><label class="form-label" for="cluster-q">Search</label><input class="form-control" id="cluster-q" name="q" value="<?= e($search) ?>" placeholder="Name, code, sitio"></div>
    <div class="col-md-3"><label class="form-label" for="cluster-barangay">Barangay</label><select class="form-select" id="cluster-barangay" name="barangay_id"><option value="">All barangays</option><?php foreach ($barangays as $barangay): ?><option value="<?= (int) $barangay['id'] ?>" <?= (int) $barangayFilter === (int) $barangay['id'] ? 'selected' : '' ?>><?= e($barangay['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-3"><label class="form-label" for="cluster-species">Species</label><select class="form-select" id="cluster-species" name="species_id"><option value="">All species</option><?php foreach ($species as $item): ?><option value="<?= (int) $item['id'] ?>" <?= (int) $speciesFilter === (int) $item['id'] ? 'selected' : '' ?>><?= e($item['common_name']) ?> — <?= e($item['scientific_name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-2"><label class="form-label" for="cluster-health">Health</label><select class="form-select" id="cluster-health" name="health"><option value="">All health</option><?php foreach ($healthValues as $health): ?><option value="<?= e($health) ?>" <?= $healthFilter === $health ? 'selected' : '' ?>><?= e($health) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-1"><button class="btn btn-success w-100" type="submit">Go</button></div>
</div></form>
<?php $canViewSurvival = ($currentUser['role'] ?? '') === 'system_admin'; ?>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Cluster</th><th>Barangay / sitio</th><th>Species</th><th>Rarity</th><th>Health</th><th class="text-end">Verified</th><?php if ($canViewSurvival): ?><th class="text-end">Survival</th><?php endif; ?><th></th></tr></thead><tbody>
<?php foreach ($clusters as $cluster): ?><tr><td><strong><?= e($cluster['cluster_code']) ?></strong><div class="small text-muted"><?= e($cluster['name']) ?></div></td><td><?= e($cluster['barangay_name']) ?><div class="small text-muted"><?= e($cluster['sitio_name'] ?: 'No sitio') ?></div></td><td><?= e($cluster['species_name'] ?: ($cluster['scientific_name'] ?: 'Unassigned')) ?></td><td><?= e($cluster['rarity_level']) ?></td><td><span class="badge <?= e(health_class($cluster['latest_health'])) ?>"><?= e($cluster['latest_health']) ?></span></td><td class="text-end"><?= number_format((int) $cluster['verified_count']) ?></td><?php if ($canViewSurvival): ?><td class="text-end"><?= $cluster['survival_rate'] === null ? 'N/A' : e(number_format((float) $cluster['survival_rate'], 1) . '%') ?></td><?php endif; ?><td class="text-end"><a class="btn btn-sm btn-success" href="<?= e(url('admin/cluster.php?id=' . $cluster['id'])) ?>">Timeline</a></td></tr><?php endforeach; ?>
<?php if ($clusters === []): ?><tr><td colspan="<?= $canViewSurvival ? 8 : 7 ?>" class="text-center text-muted py-5">No clusters match these filters.</td></tr><?php endif; ?>
</tbody></table></div></div>
